# 2026-03-04 TODO

|TODO|내용|
|:---:|:---:|
|[v]|1. GCP BigQuery에서 Polars으로 DataFrame 구축|
|[v]|2. FilePath에서 FileName를 분류하기|
|[v]|3. 파일 이름에서 '_'로 분류한 데이터값 정리하기|
|[v]|4. 만들어진 데이터프레임 병합 처리|
|[v]|5. 만들어진 데이터프레임 BigQuery에 올리기|

## 1. GCP BigQuery에서 Polars으로 DataFrame 구축

In [ ]:
!pip install -r requirements.txt

Requirement already satisfied: polars in /usr/local/python/3.12.1/lib/python3.12/site-packages (1.38.1)
Requirement already satisfied: pyarrow in /usr/local/python/3.12.1/lib/python3.12/site-packages (23.0.1)
Requirement already satisfied: google-cloud-bigquery[bqstorage,pandas] in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.40.1)
Requirement already satisfied: google-api-core<3.0.0,>=2.11.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery[bqstorage,pandas]) (2.30.0)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-cloud-bigquery[bqstorage,pandas]) (2.48.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-cloud-bigquery[bqstorage,pandas]) (2.5.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-cloud-bigquery[bqstorage,pandas]) (2.8.0)
Requirement already satisfied: packaging>=24.2.0 in /home/codespace/.local/lib/python3.12/site-packages (from google-cloud-bigquery[bqstorage,pandas]) (25.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from google-cloud-bigquery[bqstorage,pandas]) (2.9.0.post0)
Requirement already satisfied: requests<3.0.0,>=2.21.0 in /home/codespace/.local/lib/python3.12/site-packages (from google-cloud-bigquery[bqstorage,pandas]) (2.32.5)
Requirement already satisfied: google-cloud-bigquery-storage<3.0.0,>=2.18.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-cloud-bigquery[bqstorage,pandas]) (2.36.2)
Requirement already satisfied: grpcio<2.0.0,>=1.47.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-cloud-bigquery[bqstorage,pandas]) (1.78.0)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-cloud-bigquery[bqstorage,pandas]) (2.3.3)
Requirement already satisfied: pandas-gbq>=0.26.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-cloud-bigquery[bqstorage,pandas]) (0.33.0)
Requirement already satisfied: db-dtypes<2.0.0,>=1.0.4 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-cloud-bigquery[bqstorage,pandas]) (1.5.0)
Requirement already satisfied: numpy>=1.24.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from db-dtypes<2.0.0,>=1.0.4->google-cloud-bigquery[bqstorage,pandas]) (2.4.2)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.3 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery[bqstorage,pandas]) (1.72.0)
Requirement already satisfied: protobuf<7.0.0,>=4.25.8 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery[bqstorage,pandas]) (6.33.5)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery[bqstorage,pandas]) (1.27.1)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery[bqstorage,pandas]) (1.78.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery[bqstorage,pandas]) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery[bqstorage,pandas]) (46.0.5)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery[bqstorage,pandas]) (4.9.1)
Requirement already satisfied: google-crc32c<2.0.0,>=1.0.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery[bqstorage,pandas]) (1.8.0)
Requirement already satisfied: typing-extensions~=4.12 in /home/codespace/.local/lib/python3.12/site-packages (from grpcio<2.0.0,>=1.47.0->google-cloud-bigquery[bqstorage,pandas]) (4.15.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas>=1.3.0->google-cloud-bigquery[bqstorage,pandas]) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in /home/codespace/.local/lib/python3.12/site-packages (from pandas>=1.3.0->google-cloud-bigquery[bqstorage,pandas]) (2025.2)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery[bqstorage,pandas]) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/codespace/.local/lib/python3.12/site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery[bqstorage,pandas]) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/codespace/.local/lib/python3.12/site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery[bqstorage,pandas]) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/codespace/.local/lib/python3.12/site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery[bqstorage,pandas]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/codespace/.local/lib/python3.12/site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery[bqstorage,pandas]) (2025.11.12)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from rsa<5,>=3.1.4->google-auth<3.0.0,>=2.14.1->google-cloud-bigquery[bqstorage,pandas]) (0.6.2)
Requirement already satisfied: polars-runtime-32==1.38.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from polars) (1.38.1)
Requirement already satisfied: cffi>=2.0.0 in /home/codespace/.local/lib/python3.12/site-packages (from cryptography>=38.0.3->google-auth<3.0.0,>=2.14.1->google-cloud-bigquery[bqstorage,pandas]) (2.0.0)
Requirement already satisfied: pycparser in /home/codespace/.local/lib/python3.12/site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3.0.0,>=2.14.1->google-cloud-bigquery[bqstorage,pandas]) (2.23)
Requirement already satisfied: setuptools in /home/codespace/.local/lib/python3.12/site-packages (from pandas-gbq>=0.26.1->google-cloud-bigquery[bqstorage,pandas]) (80.9.0)
Requirement already satisfied: pydata-google-auth>=1.5.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas-gbq>=0.26.1->google-cloud-bigquery[bqstorage,pandas]) (1.9.1)
Requirement already satisfied: psutil>=5.9.8 in /home/codespace/.local/lib/python3.12/site-packages (from pandas-gbq>=0.26.1->google-cloud-bigquery[bqstorage,pandas]) (7.1.3)
Requirement already satisfied: google-auth-oauthlib>=0.7.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas-gbq>=0.26.1->google-cloud-bigquery[bqstorage,pandas]) (1.3.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-auth-oauthlib>=0.7.0->pandas-gbq>=0.26.1->google-cloud-bigquery[bqstorage,pandas]) (2.0.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq>=0.26.1->google-cloud-bigquery[bqstorage,pandas]) (3.3.1)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python3 -m pip install --upgrade pip

In [2]:
from google.cloud import bigquery
from google.oauth2 import service_account

key_path = '/workspaces/Psychological-counseling-researching/.key/testprojects-453622-d1f78fcce8b7.json'
credentials = service_account.Credentials.from_service_account_file(key_path)

client = bigquery.Client(credentials=credentials, project=credentials.project_id)
print(f"Client created with project: {client.project}")

Client created with project: testprojects-453622

In [3]:
import polars as pl
from google.cloud import bigquery

# Perform a query.
QUERY = open('/workspaces/Psychological-counseling-researching/1-text_data/1_test.sql', 'r', encoding='utf-8').read()

query_job = client.query(QUERY)  # API request
rows = query_job.result()  # Waits for query to finish

raw_df = pl.from_arrow(rows.to_arrow())
display(raw_df)

shape: (78_505, 4)
┌───────┬─────────────────────────────────┬─────────┬─────────────────────────────────┐
│ index ┆ FilePath                        ┆ Speaker ┆ Content                         │
│ ---   ┆ ---                             ┆ ---     ┆ ---                             │
│ i64   ┆ str                             ┆ str     ┆ str                             │
╞═══════╪═════════════════════════════════╪═════════╪═════════════════════════════════╡
│ 207   ┆ gs://testprojects-453622-unzip… ┆ 상담사  ┆ 또 그 부분에도 참 또 그렇죠.    │
│       ┆                                 ┆         ┆ 그래요. 일단 선생님 …           │
│ 206   ┆ gs://testprojects-453622-unzip… ┆ 내담자  ┆ 그래서 저는 막 야한 거 막       │
│       ┆                                 ┆         ┆ 음란물 그거 즐겨 보는 경…       │
│ 205   ┆ gs://testprojects-453622-unzip… ┆ 상담사  ┆ 물론 그 범죄에 대해서 책임을    │
│       ┆                                 ┆         ┆ 가지고 또 마땅히 또 처…         │
│ 204   ┆ gs://testprojects-453622-unzip… ┆ 내담자  ┆ 그렇죠.                         │
│ 203   ┆ gs://testprojects-453622-unzip… ┆ 상담사  ┆ 글쎄요. 저는 좀 후자적인 부분에 │
│       ┆                                 ┆         ┆ 저도 좀 어느 정도 …             │
│ …     ┆ …                               ┆ …       ┆ …                               │
│ 4     ┆ gs://testprojects-453622-unzip… ┆ 상담사  ┆ 그렇군요. 그래요 저녁은 주로    │
│       ┆                                 ┆         ┆ 혼자 드세요 아니면 어머…        │
│ 3     ┆ gs://testprojects-453622-unzip… ┆ 내담자  ┆ 저녁은 아직 안 먹었어요. 끝나고 │
│       ┆                                 ┆         ┆ 먹으려고요.                     │
│ 2     ┆ gs://testprojects-453622-unzip… ┆ 상담사  ┆ 그래요 저녁은 드셨어요? 몇 시에 │
│       ┆                                 ┆         ┆ 저녁 드세요?                    │
│ 1     ┆ gs://testprojects-453622-unzip… ┆ 내담자  ┆ 예.                             │
│ 0     ┆ gs://testprojects-453622-unzip… ┆ 상담사  ┆ 안녕하세요. 네 안녕하세요.      │
│       ┆                                 ┆         ┆ @NAME 씨 그래요. 오…            │
└───────┴─────────────────────────────────┴─────────┴─────────────────────────────────┘

# 2. FilePath에서 FileName를 분류하기

In [4]:
# FilePath에서 FileName 추출
fileNames_df = raw_df.with_columns(
	pl.col("FilePath")
	.str.split("/")
	.list.last()
	.alias("FileName")
)

display(fileNames_df.select(["FilePath", "FileName"]).head(10))

shape: (10, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ FilePath                        ┆ FileName                        │
│ ---                             ┆ ---                             │
│ str                             ┆ str                             │
╞═════════════════════════════════╪═════════════════════════════════╡
│ gs://testprojects-453622-unzip… ┆ resource_addiction_10_check_A0… │
│ gs://testprojects-453622-unzip… ┆ resource_addiction_10_check_A0… │
│ gs://testprojects-453622-unzip… ┆ resource_addiction_10_check_A0… │
│ gs://testprojects-453622-unzip… ┆ resource_addiction_10_check_A0… │
│ gs://testprojects-453622-unzip… ┆ resource_addiction_10_check_A0… │
│ gs://testprojects-453622-unzip… ┆ resource_addiction_10_check_A0… │
│ gs://testprojects-453622-unzip… ┆ resource_addiction_10_check_A0… │
│ gs://testprojects-453622-unzip… ┆ resource_addiction_10_check_A0… │
│ gs://testprojects-453622-unzip… ┆ resource_addiction_10_check_A0… │
│ gs://testprojects-453622-unzip… ┆ resource_addiction_10_check_A0… │
└─────────────────────────────────┴─────────────────────────────────┘

## 3. 파일 이름에서 '_'로 분류한 데이터값 정리하기

In [5]:
# FileName을 '_' 기준으로 분해해서 컬럼화
parsed_file_name_df = (
	fileNames_df
	.with_columns(
		pl.col("FileName")
		.str.replace(r"\.[^.]+$", "")   # 확장자 제거
		.str.split("_")
		.alias("parts")
	)
	.with_columns(
		pl.col("parts").list.get(0).alias("prefix"),
		pl.col("parts").list.get(1).alias("topic"),
		pl.col("parts").list.get(2).cast(pl.Int64, strict=False).alias("session_no"),
		pl.col("parts").list.get(3).alias("stage"),
		pl.col("parts").list.get(4).alias("file_code"),
	)
	.drop("parts")
)

# 분해된 파일명 기준 건수 집계
parsed_file_name_counts = (
	parsed_file_name_df
	.group_by(["prefix", "topic", "session_no", "stage", "file_code"])
	.len()
	.rename({"len": "row_count"})
	.sort("row_count", descending=True)
)

display(parsed_file_name_df.select(
	["index", "FileName", "prefix", "topic", "session_no", "stage", "file_code"]
).head(10))
parsed_file_name_df.shape

shape: (10, 7)
┌───────┬─────────────────────────────────┬──────────┬───────────┬────────────┬───────┬───────────┐
│ index ┆ FileName                        ┆ prefix   ┆ topic     ┆ session_no ┆ stage ┆ file_code │
│ ---   ┆ ---                             ┆ ---      ┆ ---       ┆ ---        ┆ ---   ┆ ---       │
│ i64   ┆ str                             ┆ str      ┆ str       ┆ i64        ┆ str   ┆ str       │
╞═══════╪═════════════════════════════════╪══════════╪═══════════╪════════════╪═══════╪═══════════╡
│ 207   ┆ resource_addiction_10_check_A0… ┆ resource ┆ addiction ┆ 10         ┆ check ┆ A081      │
│ 206   ┆ resource_addiction_10_check_A0… ┆ resource ┆ addiction ┆ 10         ┆ check ┆ A081      │
│ 205   ┆ resource_addiction_10_check_A0… ┆ resource ┆ addiction ┆ 10         ┆ check ┆ A081      │
│ 204   ┆ resource_addiction_10_check_A0… ┆ resource ┆ addiction ┆ 10         ┆ check ┆ A081      │
│ 203   ┆ resource_addiction_10_check_A0… ┆ resource ┆ addiction ┆ 10         ┆ check ┆ A081      │
│ 202   ┆ resource_addiction_10_check_A0… ┆ resource ┆ addiction ┆ 10         ┆ check ┆ A081      │
│ 201   ┆ resource_addiction_10_check_A0… ┆ resource ┆ addiction ┆ 10         ┆ check ┆ A081      │
│ 200   ┆ resource_addiction_10_check_A0… ┆ resource ┆ addiction ┆ 10         ┆ check ┆ A081      │
│ 199   ┆ resource_addiction_10_check_A0… ┆ resource ┆ addiction ┆ 10         ┆ check ┆ A081      │
│ 198   ┆ resource_addiction_10_check_A0… ┆ resource ┆ addiction ┆ 10         ┆ check ┆ A081      │
└───────┴─────────────────────────────────┴──────────┴───────────┴────────────┴───────┴───────────┘

(78505, 10)

## 4. 만들어진 데이터프레임 병합 처리

다음 의미입니다 (`merged_summary_df` 기준):

|**`row_count`**  
	`prefix, topic, session_no, stage, file_code, Speaker` 조합별 **행 개수**입니다.  
	예: `A081 + 내담자`의 발화가 104개면 `row_count=104`.

|**`file_code_ratio_pct`**  
	해당 `file_code`가 전체 데이터(`total_rows`)에서 차지하는 **비율(%)**입니다.  
	계산: `file_code별 row_count / total_rows * 100`  
	예: `A081`이 208/1000이면 `20.8%` (같은 file_code의 상담사/내담자 행에 동일하게 붙음).

|**`speaker_ratio_pct`**  
	해당 `Speaker`가 전체 데이터에서 차지하는 **비율(%)**입니다.  
	계산: `Speaker별 row_count / total_rows * 100`  
	예: 내담자 500/1000, 상담사 500/1000이면 각각 `50.0%`.

In [6]:
# 전체 행 수
total_rows = parsed_file_name_df.height

# 원본 데이터프레임에 윈도우 함수를 사용하여 그룹별 집계 열 추가
enriched_df = parsed_file_name_df.with_columns(
    # file_code 그룹별 행 수 계산
    pl.count().over("file_code").alias("file_code_row_count"),
    # Speaker 그룹별 행 수 계산
    pl.count().over("Speaker").alias("speaker_row_count"),
)

# 위에서 계산된 그룹별 행 수를 사용하여 비율 계산
enriched_df = enriched_df.with_columns(
    # file_code별 비율
    (pl.col("file_code_row_count") / total_rows * 100)
    .round(4)
    .alias("file_code_ratio_pct"),
    # Speaker별 비율
    (pl.col("speaker_row_count") / total_rows * 100)
    .round(4)
    .alias("speaker_ratio_pct"),
)


display(enriched_df.head(20))
enriched_df.shape

/tmp/ipykernel_53817/117543745.py:7: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  pl.count().over("file_code").alias("file_code_row_count"),
/tmp/ipykernel_53817/117543745.py:9: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  pl.count().over("Speaker").alias("speaker_row_count"),

shape: (20, 14)
┌───────┬────────────┬─────────┬────────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ index ┆ FilePath   ┆ Speaker ┆ Content    ┆ … ┆ file_code_ ┆ speaker_ro ┆ file_code_ ┆ speaker_r │
│ ---   ┆ ---        ┆ ---     ┆ ---        ┆   ┆ row_count  ┆ w_count    ┆ ratio_pct  ┆ atio_pct  │
│ i64   ┆ str        ┆ str     ┆ str        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---       │
│       ┆            ┆         ┆            ┆   ┆ u32        ┆ u32        ┆ f64        ┆ f64       │
╞═══════╪════════════╪═════════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 207   ┆ gs://testp ┆ 상담사  ┆ 또 그      ┆ … ┆ 1737       ┆ 39338      ┆ 2.2126     ┆ 50.1089   │
│       ┆ rojects-45 ┆         ┆ 부분에도   ┆   ┆            ┆            ┆            ┆           │
│       ┆ 3622-unzip ┆         ┆ 참 또      ┆   ┆            ┆            ┆            ┆           │
│       ┆ …          ┆         ┆ 그렇죠.    ┆   ┆            ┆            ┆            ┆           │
│       ┆            ┆         ┆ 그래요.    ┆   ┆            ┆            ┆            ┆           │
│       ┆            ┆         ┆ 일단       ┆   ┆            ┆            ┆            ┆           │
│       ┆            ┆         ┆ 선생님 …   ┆   ┆            ┆            ┆            ┆           │
│ 206   ┆ gs://testp ┆ 내담자  ┆ 그래서     ┆ … ┆ 1737       ┆ 39159      ┆ 2.2126     ┆ 49.8809   │
│       ┆ rojects-45 ┆         ┆ 저는 막    ┆   ┆            ┆            ┆            ┆           │
│       ┆ 3622-unzip ┆         ┆ 야한 거 막 ┆   ┆            ┆            ┆            ┆           │
│       ┆ …          ┆         ┆ 음란물     ┆   ┆            ┆            ┆            ┆           │
│       ┆            ┆         ┆ 그거 즐겨  ┆   ┆            ┆            ┆            ┆           │
│       ┆            ┆         ┆ 보는 경…   ┆   ┆            ┆            ┆            ┆           │
│ 205   ┆ gs://testp ┆ 상담사  ┆ 물론 그    ┆ … ┆ 1737       ┆ 39338      ┆ 2.2126     ┆ 50.1089   │
│       ┆ rojects-45 ┆         ┆ 범죄에     ┆   ┆            ┆            ┆            ┆           │
│       ┆ 3622-unzip ┆         ┆ 대해서     ┆   ┆            ┆            ┆            ┆           │
│       ┆ …          ┆         ┆ 책임을     ┆   ┆            ┆            ┆            ┆           │
│       ┆            ┆         ┆ 가지고 또  ┆   ┆            ┆            ┆            ┆           │
│       ┆            ┆         ┆ 마땅히 또  ┆   ┆            ┆            ┆            ┆           │
│       ┆            ┆         ┆ 처…        ┆   ┆            ┆            ┆            ┆           │
│ 204   ┆ gs://testp ┆ 내담자  ┆ 그렇죠.    ┆ … ┆ 1737       ┆ 39159      ┆ 2.2126     ┆ 49.8809   │
│       ┆ rojects-45 ┆         ┆            ┆   ┆            ┆            ┆            ┆           │
│       ┆ 3622-unzip ┆         ┆            ┆   ┆            ┆            ┆            ┆           │
│       ┆ …          ┆         ┆            ┆   ┆            ┆            ┆            ┆           │
│ 203   ┆ gs://testp ┆ 상담사  ┆ 글쎄요.    ┆ … ┆ 1737       ┆ 39338      ┆ 2.2126     ┆ 50.1089   │
│       ┆ rojects-45 ┆         ┆ 저는 좀    ┆   ┆            ┆            ┆            ┆           │
│       ┆ 3622-unzip ┆         ┆ 후자적인   ┆   ┆            ┆            ┆            ┆           │
│       ┆ …          ┆         ┆ 부분에     ┆   ┆            ┆            ┆            ┆           │
│       ┆            ┆         ┆ 저도 좀    ┆   ┆            ┆            ┆            ┆           │
│       ┆            ┆         ┆ 어느 정도  ┆   ┆            ┆            ┆            ┆           │
│       ┆            ┆         ┆ …          ┆   ┆            ┆            ┆            ┆           │
│ …     ┆ …          ┆ …       ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ 192   ┆ gs://testp ┆ 내담자  ┆ 저도       ┆ … ┆ 1737       ┆ 39159      ┆ 2.2126     ┆ 49.8809   │
│       ┆ rojects-45 ┆         ┆ 생각을     ┆   ┆            ┆            ┆            ┆           │
│       ┆ 3622-unzip ┆         ┆ 그래서     ┆   ┆            ┆            ┆            ┆           │
│       ┆ …          ┆         ┆ 어제는     ┆   ┆            ┆            ┆            ┆           │
│       ┆            ┆         ┆ 오늘       ┆   ┆            ┆            ┆            ┆           │
│       ┆            ┆         ┆ 아까도     ┆   ┆            ┆            ┆            ┆           │
│       ┆            ┆         ┆ 집에       ┆   ┆            ┆            ┆            ┆           │
│       ┆            ┆         ┆ 가면서 집… ┆   ┆            ┆            ┆            ┆           │
│ 191   ┆ gs://testp ┆ 상담사  ┆ 그러니까   ┆ … ┆ 1737       ┆ 39338      ┆ 2.2126     ┆ 50.1089   │
│       ┆ rojects-45 ┆         ┆ 이거는     ┆   ┆            ┆            ┆            ┆           │
│       ┆ 3622-unzip ┆         ┆ 이거는 뭐  ┆   ┆            ┆            ┆            ┆           │
│       ┆ …          ┆         ┆ 우리가     ┆   ┆            ┆            ┆            ┆           │
│       ┆            ┆         ┆ 우연이라고 ┆   ┆            ┆            ┆            ┆           │
│       ┆            ┆         ┆ 하기에는 … ┆   ┆            ┆            ┆            ┆           │
│ 190   ┆ gs://testp ┆ 내담자  ┆ 아무리     ┆ … ┆ 1737       ┆ 39159      ┆ 2.2126     ┆ 49.8809   │
│       ┆ rojects-45 ┆         ┆ 아다리가   ┆   ┆            ┆            ┆            ┆           │
│       ┆ 3622-unzip ┆         ┆ 잘 맞아도  ┆   ┆            ┆            ┆            ┆           │
│       ┆ …          ┆         ┆ 이렇게까지 ┆   ┆            ┆            ┆            ┆           │
│       ┆            ┆         ┆ 잘 맞을    ┆   ┆            ┆            ┆            ┆           │
│       ┆            ┆         ┆ 수가 있…   ┆   ┆            ┆            ┆            ┆           │
│ 189   ┆ gs://testp ┆ 상담사  ┆ 그러니까요 ┆ … ┆ 1737       ┆ 39338      ┆ 2.2126     ┆ 50.1089   │
│       ┆ rojects-45 ┆         ┆ .          ┆   ┆            ┆            ┆            ┆           │
│       ┆ 3622-unzip ┆         ┆            ┆   ┆            ┆            ┆            ┆           │
│       ┆ …          ┆         ┆            ┆   ┆            ┆            ┆            ┆           │
│ 188   ┆ gs://testp ┆ 내담자  ┆ 너무       ┆ … ┆ 1737       ┆ 39159      ┆ 2.2126     ┆ 49.8809   │
│       ┆ rojects-45 ┆         ┆ 아다리가.  ┆   ┆            ┆            ┆            ┆           │
│       ┆ 3622-unzip ┆         ┆            ┆   ┆            ┆            ┆            ┆           │
│       ┆ …          ┆         ┆            ┆   ┆            ┆            ┆            ┆           │
└───────┴────────────┴─────────┴────────────┴───┴────────────┴────────────┴────────────┴───────────┘

(78505, 14)

## 5. 만들어진 데이터프레임 BigQuery에 올리기

In [7]:
!pip install pandas-gbq

Requirement already satisfied: pandas-gbq in /usr/local/python/3.12.1/lib/python3.12/site-packages (0.33.0)
Requirement already satisfied: setuptools in /home/codespace/.local/lib/python3.12/site-packages (from pandas-gbq) (80.9.0)
Requirement already satisfied: db-dtypes<2.0.0,>=1.0.4 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas-gbq) (1.5.0)
Requirement already satisfied: numpy>=1.18.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas-gbq) (2.4.2)
Requirement already satisfied: pandas<3.0.0,>=1.1.4 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas-gbq) (2.3.3)
Requirement already satisfied: pyarrow>=4.0.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas-gbq) (23.0.1)
Requirement already satisfied: pydata-google-auth>=1.5.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas-gbq) (1.9.1)
Requirement already satisfied: psutil>=5.9.8 in /home/codespace/.local/lib/python3.12/site-packages (from pandas-gbq) (7.1.3)
Requirement already satisfied: google-api-core<3.0.0,>=2.15.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas-gbq) (2.30.0)
Requirement already satisfied: google-auth>=2.14.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas-gbq) (2.48.0)
Requirement already satisfied: google-auth-oauthlib>=0.7.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas-gbq) (1.3.0)
Requirement already satisfied: google-cloud-bigquery<4.0.0,>=3.20.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas-gbq) (3.40.1)
Requirement already satisfied: packaging>=22.0.0 in /home/codespace/.local/lib/python3.12/site-packages (from pandas-gbq) (25.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.3 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-api-core<3.0.0,>=2.15.0->pandas-gbq) (1.72.0)
Requirement already satisfied: protobuf<7.0.0,>=4.25.8 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-api-core<3.0.0,>=2.15.0->pandas-gbq) (6.33.5)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-api-core<3.0.0,>=2.15.0->pandas-gbq) (1.27.1)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /home/codespace/.local/lib/python3.12/site-packages (from google-api-core<3.0.0,>=2.15.0->pandas-gbq) (2.32.5)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-auth>=2.14.1->pandas-gbq) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-auth>=2.14.1->pandas-gbq) (46.0.5)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-auth>=2.14.1->pandas-gbq) (4.9.1)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq) (2.5.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq) (2.8.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq) (2.9.0.post0)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq) (1.78.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq) (1.78.0)
Requirement already satisfied: google-crc32c<2.0.0,>=1.0.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq) (1.8.0)
Requirement already satisfied: typing-extensions~=4.12 in /home/codespace/.local/lib/python3.12/site-packages (from grpcio<2.0.0,>=1.33.2->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq) (4.15.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas<3.0.0,>=1.1.4->pandas-gbq) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in /home/codespace/.local/lib/python3.12/site-packages (from pandas<3.0.0,>=1.1.4->pandas-gbq) (2025.2)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/codespace/.local/lib/python3.12/site-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.15.0->pandas-gbq) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/codespace/.local/lib/python3.12/site-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.15.0->pandas-gbq) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/codespace/.local/lib/python3.12/site-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.15.0->pandas-gbq) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/codespace/.local/lib/python3.12/site-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.15.0->pandas-gbq) (2025.11.12)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from rsa<5,>=3.1.4->google-auth>=2.14.1->pandas-gbq) (0.6.2)
Requirement already satisfied: cffi>=2.0.0 in /home/codespace/.local/lib/python3.12/site-packages (from cryptography>=38.0.3->google-auth>=2.14.1->pandas-gbq) (2.0.0)
Requirement already satisfied: pycparser in /home/codespace/.local/lib/python3.12/site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth>=2.14.1->pandas-gbq) (2.23)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-auth-oauthlib>=0.7.0->pandas-gbq) (2.0.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq) (3.3.1)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python3 -m pip install --upgrade pip

In [9]:
# 데이터프레임을 Pandas로 변환
pandas_df = enriched_df.to_pandas()

# BigQuery에 업로드
project_id = credentials.project_id
table_id = f'{project_id}.Psychological_counseling_data.processed_data'

pandas_df.to_gbq(
    destination_table=table_id,
    project_id=project_id,
    if_exists='replace',  # 테이블이 이미 존재하면 덮어쓰기
    credentials=credentials
)

print(f"Table {table_id} uploaded successfully.")

/tmp/ipykernel_53817/281438451.py:8: FutureWarning: to_gbq is deprecated and will be removed in a future version. Please use pandas_gbq.to_gbq instead: https://pandas-gbq.readthedocs.io/en/latest/api.html#pandas_gbq.to_gbq
  pandas_df.to_gbq(

Table testprojects-453622.Psychological_counseling_data.processed_data uploaded successfully.